---
name: Continuous Integration

on: push

jobs:
  tests:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install python dependencies
        run: |
          python3 -m pip install -e .[dev]

      - name: Run test suite
        run: pytest -n 4
